import type {
  ActionIntent,
  ActionResult,
  AgentBelief,
  Character,
  Observation,
  OracleRequest,
  OracleResponse,
  World,
  WorldEvent,
} from "@/types/domain";

export const demoWorld: World = {
  id: "world-harbor-lockdown",
  name: "灰港封锁区",
  description:
    "一个七日封锁城的固定演示切片，用来观察信息如何在不同角色之间不完整地传播。",
  status: "running",
  current_time: "2026-07-25T06:40:00+08:00",
  time_scale: 1,
  schema_version: "1.0",
  version: 1,
  created_at: "2026-07-23T08:00:00+08:00",
  updated_at: "2026-07-25T06:40:00+08:00",
};

export const demoCharacters: Character[] = [
  {
    id: "char-lin-zhixia",
    world_id: demoWorld.id,
    name: "林知夏",
    description: "社区诊所医生，直接面对发热病例，但没有完整政务信息。",
    age: 34,
    occupation: "社区诊所医生",
    health: 0.86,
    status: "active",
    is_special_agent: true,
    location_id: "clinic-east",
    resources: { masks: 12, medicine_days: 2 },
    schema_version: "1.0",
    version: 1,
    created_at: "2026-07-23T08:00:00+08:00",
    updated_at: "2026-07-25T06:40:00+08:00",
  },
  {
    id: "char-zhou-qiming",
    world_id: demoWorld.id,
    name: "周启明",
    description:
      "区政务处基层官员，知道部分封锁预案，但看不到医院床位真实压力。",
    age: 41,
    occupation: "区政务处基层官员",
    health: 0.92,
    status: "active",
    is_special_agent: true,
    location_id: "district-office",
    resources: { clearance_level: "restricted", radio: true },
    schema_version: "1.0",
    version: 1,
    created_at: "2026-07-23T08:00:00+08:00",
    updated_at: "2026-07-25T06:40:00+08:00",
  },
  {
    id: "char-chen-mo",
    world_id: demoWorld.id,
    name: "陈沫",
    description: "带孩子的便利店店主，只能从顾客、配送员和街面变化拼出局势。",
    age: 29,
    occupation: "便利店店主",
    health: 0.78,
    status: "active",
    is_special_agent: true,
    location_id: "north-market-store",
    resources: { water_boxes: 2, food_days: 3, child_medicine_days: 1 },
    schema_version: "1.0",
    version: 1,
    created_at: "2026-07-23T08:00:00+08:00",
    updated_at: "2026-07-25T06:40:00+08:00",
  },
];

export const demoWorldEvents: WorldEvent[] = [
  {
    id: "event-day1-fever",
    world_id: demoWorld.id,
    title: "港区医院报告异常发热病例",
    description: "第 1 日 08:00，港区医院向卫生署报告异常发热病例。",
    event_type: "system",
    occurred_at: "2026-07-23T08:00:00+08:00",
    created_at: "2026-07-23T08:01:00+08:00",
    participant_ids: ["char-lin-zhixia"],
    location_id: "harbor-hospital",
    visibility: "restricted",
    fact_ids: ["fact-fever-cluster"],
    source_action_id: null,
    correlation_id: "corr-fever-cluster",
    metadata: { day: 1, hour: "08:00" },
    schema_version: "1.0",
  },
  {
    id: "event-day1-pathogen",
    world_id: demoWorld.id,
    title: "卫生署内部确认传播速度偏高",
    description: "第 1 日 13:00，卫生署内部确认病原传播速度高于预期。",
    event_type: "system",
    occurred_at: "2026-07-23T13:00:00+08:00",
    created_at: "2026-07-23T13:03:00+08:00",
    participant_ids: [],
    location_id: "health-bureau",
    visibility: "secret",
    fact_ids: ["fact-fast-spread"],
    source_action_id: null,
    correlation_id: "corr-health-bureau",
    metadata: { day: 1, hour: "13:00" },
    schema_version: "1.0",
  },
  {
    id: "event-day2-panic-buying",
    world_id: demoWorld.id,
    title: "超市出现抢购",
    description: "第 2 日 09:00，北市集多家超市出现抢购，货架补给变慢。",
    event_type: "state_changed",
    occurred_at: "2026-07-24T09:00:00+08:00",
    created_at: "2026-07-24T09:05:00+08:00",
    participant_ids: ["char-chen-mo"],
    location_id: "north-market",
    visibility: "public",
    fact_ids: ["fact-panic-buying"],
    source_action_id: null,
    correlation_id: "corr-market-shortage",
    metadata: { day: 2, hour: "09:00" },
    schema_version: "1.0",
  },
  {
    id: "event-day2-north-gate-plan",
    world_id: demoWorld.id,
    title: "市政厅秘密批准北门封锁预案",
    description: "第 2 日 18:00，市政厅秘密批准北门封锁预案，尚未公开发布。",
    event_type: "system",
    occurred_at: "2026-07-24T18:00:00+08:00",
    created_at: "2026-07-24T18:06:00+08:00",
    participant_ids: ["char-zhou-qiming"],
    location_id: "city-hall",
    visibility: "secret",
    fact_ids: ["fact-north-gate-plan"],
    source_action_id: null,
    correlation_id: "corr-north-gate-plan",
    metadata: { day: 2, hour: "18:00" },
    schema_version: "1.0",
  },
  {
    id: "event-day3-guards",
    world_id: demoWorld.id,
    title: "北门增派守卫",
    description: "第 3 日 06:00，北门增派守卫，公共公告尚未发布。",
    event_type: "movement",
    occurred_at: "2026-07-25T06:00:00+08:00",
    created_at: "2026-07-25T06:02:00+08:00",
    participant_ids: ["char-zhou-qiming"],
    location_id: "north-gate",
    visibility: "restricted",
    fact_ids: ["fact-north-gate-guards"],
    source_action_id: null,
    correlation_id: "corr-north-gate-guards",
    metadata: { day: 3, hour: "06:00" },
    schema_version: "1.0",
  },
  {
    id: "event-chen-action-result",
    world_id: demoWorld.id,
    title: "陈沫推迟前往北门",
    description: "配送员没有接电话，但陈沫清点库存后决定暂时留在店里。",
    event_type: "state_changed",
    occurred_at: "2026-07-25T06:38:00+08:00",
    created_at: "2026-07-25T06:39:00+08:00",
    participant_ids: ["char-chen-mo"],
    location_id: "north-market-store",
    visibility: "private",
    fact_ids: ["fact-chen-delays-north-gate"],
    source_action_id: "intent-chen-contact-courier",
    correlation_id: "corr-chen-oracle-decision",
    metadata: { day: 3, hour: "06:38" },
    schema_version: "1.0",
  },
];

export const demoObservations: Observation[] = [
  {
    id: "obs-lin-fever",
    world_id: demoWorld.id,
    agent_id: "char-lin-zhixia",
    observation_type: "mixed",
    observed_at: "2026-07-23T08:20:00+08:00",
    source_event_id: "event-day1-fever",
    source_message_id: null,
    visible_entities: [
      {
        entity: { entity_type: "location", entity_id: "clinic-east" },
        name: "诊所候诊区",
        description: "等待的发热病人比平日更多。",
        attributes: { crowding: "high" },
      },
    ],
    heard_statements: [
      { speaker_id: null, content: "有人说港区医院也在收治类似症状。" },
    ],
    received_messages: [],
    felt_changes: [{ description: "诊所药品消耗速度变快", intensity: 0.7 }],
    available_actions: [
      {
        action_type: "speak",
        description: "提醒邻里减少聚集",
        parameter_hints: {},
      },
      {
        action_type: "wait",
        description: "继续观察病例变化",
        parameter_hints: {},
      },
    ],
    metadata: { perspective_note: "不知道北门封锁预案。" },
    schema_version: "1.0",
  },
  {
    id: "obs-zhou-plan",
    world_id: demoWorld.id,
    agent_id: "char-zhou-qiming",
    observation_type: "message",
    observed_at: "2026-07-24T18:18:00+08:00",
    source_event_id: "event-day2-north-gate-plan",
    source_message_id: "msg-city-hall-plan",
    visible_entities: [],
    heard_statements: [],
    received_messages: [
      {
        message_id: "msg-city-hall-plan",
        sender_id: null,
        sent_at: "2026-07-24T18:12:00+08:00",
        content: "北门管控方案已进入预备状态，等待公开口径。",
      },
    ],
    felt_changes: [{ description: "办公室进入低声通话状态", intensity: 0.5 }],
    available_actions: [
      {
        action_type: "speak",
        description: "向上级请求可公开信息",
        parameter_hints: {},
      },
      { action_type: "wait", description: "等待正式公告", parameter_hints: {} },
    ],
    metadata: { perspective_note: "不知道诊所实际床位压力。" },
    schema_version: "1.0",
  },
  {
    id: "obs-chen-rumor",
    world_id: demoWorld.id,
    agent_id: "char-chen-mo",
    observation_type: "auditory",
    observed_at: "2026-07-25T06:12:00+08:00",
    source_event_id: "event-day3-guards",
    source_message_id: null,
    visible_entities: [
      {
        entity: { entity_type: "location", entity_id: "north-market-street" },
        name: "北市集街口",
        description: "街口有人急着往北门方向走，也有人劝他们回头。",
        attributes: { visibility: "partial" },
      },
    ],
    heard_statements: [
      { speaker_id: null, content: "北门可能已经关了，晚了就出不去了。" },
      { speaker_id: null, content: "守卫只是换班，公告还没出来。" },
    ],
    received_messages: [],
    felt_changes: [{ description: "店里顾客明显焦躁", intensity: 0.8 }],
    available_actions: [
      {
        action_type: "custom",
        description: "请求玩家提供启示",
        parameter_hints: {},
      },
      {
        action_type: "wait",
        description: "留在店里继续核实消息",
        parameter_hints: {},
      },
    ],
    metadata: { perspective_note: "只听到传言和街面变化。" },
    schema_version: "1.0",
  },
];

export const demoBeliefs: AgentBelief[] = [
  {
    id: "belief-lin-fever-risk",
    world_id: demoWorld.id,
    agent_id: "char-lin-zhixia",
    subject: "发热病例",
    predicate: "正在异常增加",
    object: "诊所和医院可能同时承压",
    confidence: 0.78,
    source_type: "observation",
    source_id: "obs-lin-fever",
    learned_at: "2026-07-23T08:25:00+08:00",
    last_updated_at: "2026-07-24T09:00:00+08:00",
    schema_version: "1.0",
  },
  {
    id: "belief-zhou-north-gate",
    world_id: demoWorld.id,
    agent_id: "char-zhou-qiming",
    subject: "北门",
    predicate: "可能进入管控",
    object: "公开公告前不能向居民确认",
    confidence: 0.86,
    source_type: "message",
    source_id: "msg-city-hall-plan",
    learned_at: "2026-07-24T18:18:00+08:00",
    last_updated_at: "2026-07-25T06:00:00+08:00",
    schema_version: "1.0",
  },
  {
    id: "belief-chen-lockdown-started",
    world_id: demoWorld.id,
    agent_id: "char-chen-mo",
    subject: "北门封锁",
    predicate: "也许已经开始",
    object: "需要决定是否带孩子离开",
    confidence: 0.42,
    source_type: "observation",
    source_id: "obs-chen-rumor",
    learned_at: "2026-07-25T06:12:00+08:00",
    last_updated_at: "2026-07-25T06:22:00+08:00",
    schema_version: "1.0",
  },
];

export const demoOracleRequest: OracleRequest = {
  id: "oracle-request-chen-north-gate",
  world_id: demoWorld.id,
  agent_id: "char-chen-mo",
  question: "是否应该带孩子连夜前往北门，还是留在店里等待消息？",
  context_summary: "陈沫听到北门传言，库存有限，孩子还需要药物。",
  decision_correlation_id: "corr-chen-oracle-decision",
  requested_at: "2026-07-25T06:20:00+08:00",
  world_deadline: "2026-07-25T07:00:00+08:00",
  real_deadline: null,
  status: "answered",
  schema_version: "1.0",
};

export const demoOracleResponse: OracleResponse = {
  id: "oracle-response-chen-north-gate",
  world_id: demoWorld.id,
  agent_id: "char-chen-mo",
  request_id: demoOracleRequest.id,
  content:
    "先不要冒险冲向北门，确认孩子药物和食物，找一个可信的人核实守卫调动。",
  clarity: 0.74,
  responded_at: "2026-07-25T06:27:00+08:00",
  schema_version: "1.0",
};

export const demoActionIntent: ActionIntent = {
  id: "intent-chen-contact-courier",
  world_id: demoWorld.id,
  actor_id: "char-chen-mo",
  action_type: "custom",
  reason_summary:
    "陈沫把玩家启示当作一条信息来源，尝试联系熟悉的配送员并整理三天食物。",
  parameters: {
    target: "courier-friend",
    preparation: ["call_courier", "count_food", "delay_north_gate"],
  },
  expected_duration: 0.4,
  submitted_at: "2026-07-25T06:31:00+08:00",
  correlation_id: "corr-chen-oracle-decision",
  schema_version: "1.0",
};

export const demoActionResult: ActionResult = {
  id: "result-chen-contact-courier",
  world_id: demoWorld.id,
  action_id: demoActionIntent.id,
  actor_id: "char-chen-mo",
  status: "succeeded",
  started_at: "2026-07-25T06:32:00+08:00",
  completed_at: "2026-07-25T06:38:00+08:00",
  correlation_id: "corr-chen-oracle-decision",
  failure_code: null,
  failure_reason: null,
  generated_event_ids: ["event-chen-action-result"],
  witness_character_ids: ["char-chen-mo"],
  state_changes: [
    {
      entity_type: "character",
      entity_id: "char-chen-mo",
      field: "resources.water_boxes",
      old_value: "unknown",
      new_value: 2,
    },
  ],
  schema_version: "1.0",
};
